### PR TITLE
Heroically added missing brace

### PR DESCRIPTION
**Pull request by elimisteve**

### CODE REVIEW

**Comment by arturovm** [comment]
Yes! Quite the hero :P Thanks.
Wanna hop on board? Still some interesting design decisions to take.

**Comment by elimisteve** [comment]
Can you create a README.md that describes what it is you're doing?

**Comment by elimisteve** [comment]
And the app/repo description :-)

**Comment by arturovm** [comment]
Sure. But just not yet :P 
You can have a look at this, though: http://arturovm.github.io/pond/

**Pull request merged**
